const cfg=window.WBSC_CONFIG||{};let snapshot=null,timer=null,lastGood=null;export const $=id=>document.getElementById(id);export const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));export const clean=v=>String(v??'').replaceAll('&lt;br&gt;','\n').replaceAll('<br>','\n');
async function text(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return(await r.text()).trim()}
async function cycle(render){try{const base=`https://game.wbsc.org/gamedata/${cfg.gameId}`;const n=await text(`${base}/latest.json`);if(!/^\d+$/.test(n))throw Error('latest.json non contiene un numero');if(n!==snapshot||!lastGood){const r=await fetch(`${base}/play${n}.json?_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`play${n}.json: HTTP ${r.status}`);const g=await r.json();if(String(g.gameid)!==String(cfg.gameId))throw Error('Game ID non corrispondente');snapshot=n;lastGood=g}render(lastGood,{snapshot:n,final:Number(lastGood.gameover)!==0||lastGood.situation?.currentinning==='FINAL'});document.querySelector('.status')?.classList.remove('show')}catch(e){const x=document.querySelector('.status');if(x){x.textContent=e.message;x.classList.add('show')}if(lastGood)render(lastGood,{snapshot,stale:true})}}
export function start(render){cycle(render);timer=setInterval(()=>cycle(render),Math.max(750,Number(cfg.refreshMs)||1000))}
export function hitters(g,team){return Object.entries(g.boxscore||{}).filter(([,p])=>p.teamcode===team&&Object.hasOwn(p,'POS')).sort((a,b)=>Number(a[0])-Number(b[0]))}
export function pitchers(g,team){return Object.entries(g.boxscore||{}).filter(([,p])=>p.teamcode===team&&Object.hasOwn(p,'PITCHIP')).sort((a,b)=>Number(a[0])-Number(b[0]))}
export function seasonAvg(p){const s=p.SEASON||{},ab=Number(s.AB||0),h=Number(s.H||0);return ab?'.'+Math.round(h/ab*1000).toString().padStart(3,'0'):'.000'}
export function finalPosition(p){return String(p.POS||'').split('/').filter(Boolean).at(-1)||''}
export function currentDefense(g,team){const map=new Map();for(const [key,p] of hitters(g,team)){const pos=finalPosition(p);if(!['PH','PR','DH','DP','OPO'].includes(pos)&&p.reentry===0)map.set(pos,p);if(p.reentry)map.set(pos,p)}return map}
